apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-api-luizalabs-deployment
  labels:
    app: cliente-api-luizalabs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cliente-api-luizalabs
  template:
    metadata:
      labels:
        app: cliente-api-luizalabs
        name: cliente-api-luizalabs-pod
    spec:
      containers:
      - name: cliente-api-luizalabs-container
        image: cliente-api-luizalabs
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 5
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 5
      restartPolicy: Always
      
---

apiVersion: v1
kind: Service
metadata:
  name: cliente-api-luizalabs-service
  labels:
    name: cliente-api-luizalabs
spec:
  selector:
    app: cliente-api-luizalabs
  type: NodePort
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 8090
      targetPort: 8090
