apiVersion: v1
kind: Service
metadata:
  name: cliente-api-luizalabs-service
  labels:
    name: cliente-api-luizalabs
spec:
  selector:
    app: cliente-api-luizalabs
  type: NodePort
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 8090
      targetPort: 8090