version: "3.1"

services:
  
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user_root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - /volume/mongo/setup.:/setup
      - /volume/mongo/data.:/data/db
    command: --auth